apiVersion: v1
kind: Pod
metadata:
  name: host-topo-job
spec:
  nodeName: "REPLACE_NODE_NAME"  # Will be replaced by run_job_pod.sh
  hostNetwork: true
  restartPolicy: Never

  terminationGracePeriodSeconds: 0

  volumes:
  - name: output-volume
    emptyDir: {}
  - name: host-sys
    hostPath:
      path: /sys
      type: Directory
  
  containers:
  - name: topo-vis-container
    image: ghcr.io/harvard-cns/host-topo-vis:latest
    securityContext:
      privileged: true
    resources:
      requests:
        nvidia.com/gpu: REPLACE_NVIDIA_GPU_COUNT
        amd.com/gpu: REPLACE_AMD_GPU_COUNT
        REPLACE_RDMA_RESOURCE
      limits:
        nvidia.com/gpu: REPLACE_NVIDIA_GPU_COUNT
        amd.com/gpu: REPLACE_AMD_GPU_COUNT
        REPLACE_RDMA_RESOURCE
    volumeMounts:
    - name: output-volume
      mountPath: /output
    - name: host-sys
      mountPath: /sys
      readOnly: true
  # This is a helper container that will wait for the topo-vis-container to finish and 
  # then allow copying the output files to the client.
  - name: helper-container
    image: quay.io/quay/busybox:latest
    volumeMounts:
    - name: output-volume
      mountPath: /output
    command: ["/bin/sleep", "3600"]
  